name: mini-bookstore

services:
  # backend:
  #   build:
  #     context: ./backend
  #     dockerfile: Dockerfile

  #   ports:
  #     - "8080:8080"

  #   volumes:
  #     # Mount local source code into container
  #     - ./backend:/app

  #     # Prevent overwriting container gradle cache
  #     - gradle-cache:/root/.gradle

  #   environment:
  #     SPRING_DEVTOOLS_RESTART_ENABLED: "true"

  #     # MySQL
  #     SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/ministore
  #     SPRING_DATASOURCE_USERNAME: root
  #     SPRING_DATASOURCE_PASSWORD: root

  #     # Redis
  #     SPRING_DATA_REDIS_HOST: redis
  #     SPRING_DATA_REDIS_PORT: 6379

  #     # Kafka
  #     SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092

  #   depends_on:
  #     - mysql
  #     - redis
  #     - kafka

  #   stdin_open: true
  #   tty: true

  mysql:
    image: mysql:8.4
    container_name: mini-bookstore-mysql
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: ministore
    volumes:
      - mysql-data:/var/lib/mysql

  redis:
    image: redis:alpine
    container_name: mini-bookstore-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

  zookeeper:
    image: confluentinc/cp-zookeeper:7.3.5
    container_name: mini-bookstore-zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:7.3.5
    container_name: mini-bookstore-kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

volumes:
  gradle-cache:
  mysql-data:
  redis-data:
