spring.application.name=mini-bookstore
server.port=3010

jwt.secret=fdsajhjift7387afklfgalkfjlasdfhy
jwt.expiration-ms=86400000

# ─── MySQL ──────────────────────────────────────────
spring.datasource.url=jdbc:mysql://localhost:3306/mini_bookstore?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=password
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

# Kafka
spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.consumer.group-id=myGroup